### ISSUE TITLE
"easy-to-use" might not apply

### ISSUE THREAD

**Issue by slyphix** [lazyguyy/bingo-generator#1]
So you either need to have a working LaTeX installation or you have to make your own template from scratch? I do not think "easy-to-use" applies here. You might want to rethink that. Other than that, I guess it is fine.

**Comment by lazyguyy** [comment]
Well, if you are unable to make LaTeX work on your computer, you might as well just stop using computers altogether. I guess you're one of those persons who write scientific papers with Word and don't bother with LaTeX, because it is too complicated for their simple minds.
If you can come up with any "real" issues, I'll gladly fix them, but for now I'd ask you to stop wasting my time with this garbage.

in case people cannot tell: this is banter between friends, I know slyphix very well personally.
